version: '3'
services:
  db-postgres:
    container_name: db-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  django:
    container_name: django
    build: .
    command: python manage.py runserver 0.0.0.0:8900
    volumes:
      - .:/code
    ports:
      - "8900:8900"
    depends_on:
      - db-postgres
  run-script:
    container_name: run-script
    build: .
    command: sh run_script.sh
    volumes:
      - .:/code
    depends_on:
      - django