# Generated by Django 4.1.6 on 2023-02-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9, unique=True)),
                ('logradouro', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('localidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('ibge', models.CharField(blank=True, max_length=10, null=True)),
                ('gia', models.CharField(blank=True, max_length=10, null=True)),
                ('ddd', models.CharField(blank=True, max_length=3, null=True)),
                ('siafi', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
