# Generated by Django 4.1.6 on 2023-02-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cep',
            name='id',
        ),
        migrations.AlterField(
            model_name='cep',
            name='cep',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
