# Generated by Django 4.1.6 on 2023-02-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cep',
            name='lojacorr',
            field=models.BooleanField(default=False),
        ),
    ]
