# Generated by Django 4.1.6 on 2023-02-11 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cep_lojacorr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('uf', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='CepsLojaCorr',
        ),
        migrations.AddField(
            model_name='cep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cep',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
