# Generated by Django 4.1.6 on 2023-02-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cep_created_at_alter_cep_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='created_at',
            field=models.CharField(default='11-02-2023 14:45:35', max_length=100),
        ),
        migrations.AlterField(
            model_name='estado',
            name='updated_at',
            field=models.CharField(default='11-02-2023 14:45:35', max_length=100),
        ),
    ]
