# Generated by Django 4.1.6 on 2023-02-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_estado_created_at_alter_estado_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cep',
            name='created_at',
            field=models.CharField(default='11-02-2023 15:00:40', max_length=100),
        ),
        migrations.AlterField(
            model_name='cep',
            name='updated_at',
            field=models.CharField(default='11-02-2023 15:00:40', max_length=100),
        ),
        migrations.AlterField(
            model_name='estado',
            name='created_at',
            field=models.CharField(default='11-02-2023 15:00:40', max_length=100),
        ),
        migrations.AlterField(
            model_name='estado',
            name='updated_at',
            field=models.CharField(default='11-02-2023 15:00:40', max_length=100),
        ),
    ]
