# Generated by Django 4.1.6 on 2023-02-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_cepslojacorr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cep',
            old_name='cidade',
            new_name='localidade',
        ),
        migrations.RenameField(
            model_name='cep',
            old_name='estado',
            new_name='uf',
        ),
        migrations.AddField(
            model_name='cep',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cep',
            name='ddd',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='cep',
            name='gia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cep',
            name='ibge',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cep',
            name='siafi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cep',
            name='cep',
            field=models.CharField(max_length=9),
        ),
    ]
